-- Script de creación para la tabla PEDIDOS_COMERCIALES
-- Generado para el entorno DEV

CREATE TABLE IF NOT EXISTS pedidos_comerciales (
    ID SERIAL PRIMARY KEY,
    PLANTA VARCHAR(100),
    ORDEN_BETA VARCHAR(50),
    PO VARCHAR(100),
    CULTIVO VARCHAR(50),
    CLIENTE VARCHAR(200),
    CONSIGNATARIO VARCHAR(200),
    RECIBIDOR VARCHAR(200),
    PORT_ID_ORIGEN VARCHAR(100),
    PAIS VARCHAR(100),
    POD VARCHAR(100),
    PORT_ID_DESTINO VARCHAR(100),
    PRESENTACION VARCHAR(100),
    VARIEDAD VARCHAR(100),
    PRODUCT VARCHAR(150),
    PESO_POR_CAJA NUMERIC(10, 2),
    ADDITIONAL_INFO TEXT,
    CAJA_POR_PALLET NUMERIC(10, 2),
    TOTAL_PALLETS NUMERIC(10, 2),
    TOTAL_CAJAS NUMERIC(10, 2),
    INCOTERM VARCHAR(50),
    TIPO_PRECIO VARCHAR(50),
    FECHA_ACTUALIZACION TIMESTAMPTZ DEFAULT NOW()
);

-- Índices para mejorar el rendimiento de cruce con Posicionamientos
CREATE INDEX IF NOT EXISTS idx_pedidos_orden_beta ON pedidos_comerciales(ORDEN_BETA);
CREATE INDEX IF NOT EXISTS idx_pedidos_cultivo ON pedidos_comerciales(CULTIVO);
