"""add ie_models for shipping instructions

Revision ID: 0189bd1cbc11
Revises: 7fef2cb052da
Create Date: 2026-03-05 15:48:53.554968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0189bd1cbc11'
down_revision: Union[str, Sequence[str], None] = '7fef2cb052da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
