"""Add logistica_facturas true

Revision ID: 074158972fb1
Revises: 1db818e3ecc3
Create Date: 2026-02-26 18:01:48.406976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '074158972fb1'
down_revision: Union[str, Sequence[str], None] = '1db818e3ecc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logistica_facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_ruc', sa.String(length=20), nullable=False),
    sa.Column('proveedor_razon_social', sa.String(length=200), nullable=False),
    sa.Column('serie_correlativo', sa.String(length=50), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contenedor', sa.String(length=50), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proveedor_ruc', 'serie_correlativo', name='uq_factura_log_ruc_serie')
    )
    op.create_table('logistica_factura_detalles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('unidad_medida', sa.String(length=10), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('valor_item', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['logistica_facturas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sap_factura_detalles')
    op.drop_table('sap_facturas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sap_facturas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('proveedor_ruc', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('proveedor_razon_social', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('serie_correlativo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('fecha_emision', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_pago', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('moneda', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('subtotal', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('contenedor', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('creado_en', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('sap_facturas_pkey')),
    sa.UniqueConstraint('proveedor_ruc', 'serie_correlativo', name=op.f('uq_factura_ruc_serie'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('sap_factura_detalles',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('factura_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('unidad_medida', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('valor_unitario', sa.NUMERIC(precision=12, scale=4), autoincrement=False, nullable=False),
    sa.Column('valor_item', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['sap_facturas.id'], name=op.f('sap_factura_detalles_factura_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sap_factura_detalles_pkey'))
    )
    op.drop_table('logistica_factura_detalles')
    op.drop_table('logistica_facturas')
    # ### end Alembic commands ###
