"""Add total_pallet to RefPosicionamiento

Revision ID: 14f9b27933f2
Revises: 8cbbf3bdf54b
Create Date: 2026-03-18 13:01:35.172157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f9b27933f2'
down_revision: Union[str, Sequence[str], None] = '8cbbf3bdf54b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ref_posicionamiento', sa.Column('total_pallet', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ref_posicionamiento', 'total_pallet')
    # ### end Alembic commands ###
