"""add valor_fob to ref_posicionamiento

Revision ID: 1c4f96475710
Revises: ac2546b2bc9c
Create Date: 2026-03-21 15:36:16.501635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c4f96475710'
down_revision: Union[str, Sequence[str], None] = 'ac2546b2bc9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ref_posicionamiento', sa.Column('valor_fob', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ref_posicionamiento', 'valor_fob')
    # ### end Alembic commands ###
