"""Add logistica_facturas

Revision ID: 1db818e3ecc3
Revises: f2618ae8a986
Create Date: 2026-02-26 17:47:08.400858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db818e3ecc3'
down_revision: Union[str, Sequence[str], None] = 'f2618ae8a986'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sap_facturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proveedor_ruc', sa.String(length=20), nullable=False),
    sa.Column('proveedor_razon_social', sa.String(length=200), nullable=False),
    sa.Column('serie_correlativo', sa.String(length=50), nullable=False),
    sa.Column('fecha_emision', sa.Date(), nullable=True),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('contenedor', sa.String(length=50), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proveedor_ruc', 'serie_correlativo', name='uq_factura_ruc_serie')
    )
    op.create_table('sap_factura_detalles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factura_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=500), nullable=False),
    sa.Column('unidad_medida', sa.String(length=10), nullable=False),
    sa.Column('valor_unitario', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('valor_item', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['factura_id'], ['sap_facturas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sap_factura_detalles')
    op.drop_table('sap_facturas')
    # ### end Alembic commands ###
