"""Add humedad and filtros to RefPosicionamiento

Revision ID: 2abe1960980b
Revises: 14f9b27933f2
Create Date: 2026-03-18 15:40:54.304518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2abe1960980b'
down_revision: Union[str, Sequence[str], None] = '14f9b27933f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ref_posicionamiento', sa.Column('humedad', sa.String(length=50), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('filtros', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ref_posicionamiento', 'filtros')
    op.drop_column('ref_posicionamiento', 'humedad')
    # ### end Alembic commands ###
