"""create ie_models tables

Revision ID: 3b59aea0eec0
Revises: 4a0e22f8952f
Create Date: 2026-03-05 17:10:52.545682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b59aea0eec0'
down_revision: Union[str, Sequence[str], None] = '4a0e22f8952f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat_clientes_ie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_comercial', sa.String(length=200), nullable=False),
    sa.Column('destino', sa.String(length=200), nullable=True),
    sa.Column('cultivo', sa.String(length=50), nullable=False),
    sa.Column('pais', sa.String(length=100), nullable=True),
    sa.Column('eori_consignatario', sa.String(length=100), nullable=True),
    sa.Column('consignatario_bl', sa.Text(), nullable=True),
    sa.Column('datos_referenciales_consignatario', sa.Text(), nullable=True),
    sa.Column('eori_notify', sa.String(length=100), nullable=True),
    sa.Column('notificante_bl', sa.Text(), nullable=True),
    sa.Column('datos_referenciales_notify', sa.Text(), nullable=True),
    sa.Column('emision_bl', sa.String(length=50), nullable=True),
    sa.Column('cliente_fito', sa.Text(), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cat_clientes_ie_cultivo'), 'cat_clientes_ie', ['cultivo'], unique=False)
    op.create_index(op.f('ix_cat_clientes_ie_destino'), 'cat_clientes_ie', ['destino'], unique=False)
    op.create_index(op.f('ix_cat_clientes_ie_nombre_comercial'), 'cat_clientes_ie', ['nombre_comercial'], unique=False)
    op.create_table('cat_plantas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('direccion', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cat_plantas_nombre'), 'cat_plantas', ['nombre'], unique=True)
    op.create_table('ie_registros_historial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking', sa.String(length=50), nullable=False),
    sa.Column('o_beta', sa.String(length=50), nullable=True),
    sa.Column('cultivo', sa.String(length=50), nullable=True),
    sa.Column('cliente', sa.String(length=200), nullable=True),
    sa.Column('fecha_generacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('creado_por', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ie_registros_historial_booking'), 'ie_registros_historial', ['booking'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ie_registros_historial_booking'), table_name='ie_registros_historial')
    op.drop_table('ie_registros_historial')
    op.drop_index(op.f('ix_cat_plantas_nombre'), table_name='cat_plantas')
    op.drop_table('cat_plantas')
    op.drop_index(op.f('ix_cat_clientes_ie_nombre_comercial'), table_name='cat_clientes_ie')
    op.drop_index(op.f('ix_cat_clientes_ie_destino'), table_name='cat_clientes_ie')
    op.drop_index(op.f('ix_cat_clientes_ie_cultivo'), table_name='cat_clientes_ie')
    op.drop_table('cat_clientes_ie')
    # ### end Alembic commands ###
