"""Add separate cert fields to Vehiculo

Revision ID: 470ff21bf728
Revises: d4e5f6a7b8c9
Create Date: 2026-02-17 16:01:20.366769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '470ff21bf728'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ope_registro_eventos_registro_id'), table_name='ope_registro_eventos')
    op.drop_table('ope_registro_eventos')
    op.alter_column('auth_usuarios', 'creado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('auth_usuarios', 'actualizado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('cat_vehiculos', sa.Column('cert_tracto', sa.String(length=50), nullable=True))
    op.add_column('cat_vehiculos', sa.Column('cert_carreta', sa.String(length=50), nullable=True))
    op.alter_column('cat_vehiculos', 'cert_vehicular',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_index(op.f('ux_his_unicos_awb_vigente'), table_name='his_unicos', postgresql_where="(((tipo)::text = 'AWB'::text) AND (vigente = true))")
    op.drop_index(op.f('ux_his_unicos_historicos_tipo_valor'), table_name='his_unicos', postgresql_where="((tipo)::text = ANY ((ARRAY['O_BETA'::character varying, 'BOOKING'::character varying, 'TERMOGRAFO'::character varying, 'PS_BETA'::character varying, 'PS_ADUANA'::character varying, 'PS_OPERADOR'::character varying, 'SENASA_PS_LINEA'::character varying])::text[]))")
    op.create_unique_constraint('uq_unicos_tipo_valor', 'his_unicos', ['tipo', 'valor'])
    op.drop_index(op.f('ix_ope_registros_estado'), table_name='ope_registros')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ope_registros_estado'), 'ope_registros', ['estado'], unique=False)
    op.drop_constraint('uq_unicos_tipo_valor', 'his_unicos', type_='unique')
    op.create_index(op.f('ux_his_unicos_historicos_tipo_valor'), 'his_unicos', ['tipo', 'valor'], unique=True, postgresql_where="((tipo)::text = ANY ((ARRAY['O_BETA'::character varying, 'BOOKING'::character varying, 'TERMOGRAFO'::character varying, 'PS_BETA'::character varying, 'PS_ADUANA'::character varying, 'PS_OPERADOR'::character varying, 'SENASA_PS_LINEA'::character varying])::text[]))")
    op.create_index(op.f('ux_his_unicos_awb_vigente'), 'his_unicos', ['tipo', 'valor'], unique=True, postgresql_where="(((tipo)::text = 'AWB'::text) AND (vigente = true))")
    op.alter_column('cat_vehiculos', 'cert_vehicular',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=True)
    op.drop_column('cat_vehiculos', 'cert_carreta')
    op.drop_column('cat_vehiculos', 'cert_tracto')
    op.alter_column('auth_usuarios', 'actualizado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('auth_usuarios', 'creado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('ope_registro_eventos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('registro_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('accion', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('antes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('despues', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('motivo', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('usuario', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('creado_en', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['registro_id'], ['ope_registros.id'], name=op.f('ope_registro_eventos_registro_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('ope_registro_eventos_pkey'))
    )
    op.create_index(op.f('ix_ope_registro_eventos_registro_id'), 'ope_registro_eventos', ['registro_id'], unique=False)
    # ### end Alembic commands ###
