"""expand ie_models with destination and history

Revision ID: 4a0e22f8952f
Revises: 0189bd1cbc11
Create Date: 2026-03-05 16:51:11.178602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a0e22f8952f'
down_revision: Union[str, Sequence[str], None] = '0189bd1cbc11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
