"""expand_ref_posicionamiento_v3

Revision ID: 51dd54c055f2
Revises: 074158972fb1
Create Date: 2026-03-04 15:48:19.177720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51dd54c055f2'
down_revision: Union[str, Sequence[str], None] = '074158972fb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ref_booking_dam', sa.Column('awb', sa.String(length=50), nullable=True))
    op.alter_column('ref_booking_dam', 'booking',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('ref_booking_dam', 'dam',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.String(length=50),
               nullable=True)
    op.create_foreign_key(None, 'ref_booking_dam', 'ref_posicionamiento', ['booking'], ['booking'])
    op.add_column('ref_posicionamiento', sa.Column('status_fcl', sa.String(length=50), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('status_beta_text', sa.String(length=100), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('planta_empacadora', sa.String(length=150), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('etd_booking', sa.String(length=50), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('eta_booking', sa.String(length=50), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('week_eta_booking', sa.String(length=20), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('dias_tt_booking', sa.Integer(), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('etd_final', sa.String(length=50), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('eta_final', sa.String(length=50), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('week_eta_real', sa.String(length=20), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('dias_tt_real', sa.Integer(), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('week_debe_arribar', sa.String(length=20), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('o_beta_inicial', sa.String(length=50), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('orden_beta_final', sa.String(length=50), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('cliente', sa.String(length=150), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('recibidor', sa.String(length=150), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('destino_pedido', sa.String(length=150), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('po_number', sa.String(length=100), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('destino_booking', sa.String(length=150), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('pais_booking', sa.String(length=100), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('nro_fcl', sa.String(length=100), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('deposito_retiro', sa.String(length=150), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('operador', sa.String(length=100), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('termoregistros', sa.String(length=150), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('hora_solicitada_operador', sa.String(length=50), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('fecha_real_llenado', sa.String(length=50), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('week_llenado', sa.String(length=20), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('variedad', sa.String(length=100), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('tipo_caja', sa.String(length=100), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('etiqueta_caja', sa.String(length=100), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('presentacion', sa.String(length=150), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('calibre', sa.String(length=50), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('cj_kg', sa.String(length=50), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('total_unidades', sa.String(length=50), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('incoterm', sa.String(length=50), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('flete', sa.String(length=50), nullable=True))
    op.alter_column('ref_posicionamiento', 'ac_option',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('ref_posicionamiento', 'ct_option',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.drop_column('ref_posicionamiento', 'es_reprogramado')
    op.drop_column('ref_posicionamiento', 'awb')
    op.drop_column('ref_posicionamiento', 'operador_logistico')
    op.drop_column('ref_posicionamiento', 'hora_posicionamiento')
    op.drop_column('ref_posicionamiento', 'o_beta')
    op.drop_column('ref_posicionamiento', 'planta_llenado')
    op.drop_column('ref_posicionamiento', 'pod')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ref_posicionamiento', sa.Column('pod', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('planta_llenado', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('o_beta', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('hora_posicionamiento', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('operador_logistico', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('awb', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('es_reprogramado', sa.INTEGER(), autoincrement=False, nullable=True))
    op.alter_column('ref_posicionamiento', 'ct_option',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('ref_posicionamiento', 'ac_option',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('ref_posicionamiento', 'flete')
    op.drop_column('ref_posicionamiento', 'incoterm')
    op.drop_column('ref_posicionamiento', 'total_unidades')
    op.drop_column('ref_posicionamiento', 'cj_kg')
    op.drop_column('ref_posicionamiento', 'calibre')
    op.drop_column('ref_posicionamiento', 'presentacion')
    op.drop_column('ref_posicionamiento', 'etiqueta_caja')
    op.drop_column('ref_posicionamiento', 'tipo_caja')
    op.drop_column('ref_posicionamiento', 'variedad')
    op.drop_column('ref_posicionamiento', 'week_llenado')
    op.drop_column('ref_posicionamiento', 'fecha_real_llenado')
    op.drop_column('ref_posicionamiento', 'hora_solicitada_operador')
    op.drop_column('ref_posicionamiento', 'termoregistros')
    op.drop_column('ref_posicionamiento', 'operador')
    op.drop_column('ref_posicionamiento', 'deposito_retiro')
    op.drop_column('ref_posicionamiento', 'nro_fcl')
    op.drop_column('ref_posicionamiento', 'pais_booking')
    op.drop_column('ref_posicionamiento', 'destino_booking')
    op.drop_column('ref_posicionamiento', 'po_number')
    op.drop_column('ref_posicionamiento', 'destino_pedido')
    op.drop_column('ref_posicionamiento', 'recibidor')
    op.drop_column('ref_posicionamiento', 'cliente')
    op.drop_column('ref_posicionamiento', 'orden_beta_final')
    op.drop_column('ref_posicionamiento', 'o_beta_inicial')
    op.drop_column('ref_posicionamiento', 'week_debe_arribar')
    op.drop_column('ref_posicionamiento', 'dias_tt_real')
    op.drop_column('ref_posicionamiento', 'week_eta_real')
    op.drop_column('ref_posicionamiento', 'eta_final')
    op.drop_column('ref_posicionamiento', 'etd_final')
    op.drop_column('ref_posicionamiento', 'dias_tt_booking')
    op.drop_column('ref_posicionamiento', 'week_eta_booking')
    op.drop_column('ref_posicionamiento', 'eta_booking')
    op.drop_column('ref_posicionamiento', 'etd_booking')
    op.drop_column('ref_posicionamiento', 'planta_empacadora')
    op.drop_column('ref_posicionamiento', 'status_beta_text')
    op.drop_column('ref_posicionamiento', 'status_fcl')
    op.drop_constraint(None, 'ref_booking_dam', type_='foreignkey')
    op.alter_column('ref_booking_dam', 'dam',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=40),
               nullable=False)
    op.alter_column('ref_booking_dam', 'booking',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('ref_booking_dam', 'awb')
    # ### end Alembic commands ###
