"""add ce_awb and alerta_discrepancia to ref_booking_dam

Revision ID: 7fef2cb052da
Revises: 51dd54c055f2
Create Date: 2026-03-05 09:47:37.744525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fef2cb052da'
down_revision: Union[str, Sequence[str], None] = '51dd54c055f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ref_booking_dam', sa.Column('ce_awb', sa.String(length=100), nullable=True))
    op.add_column('ref_booking_dam', sa.Column('alerta_discrepancia', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ref_booking_dam', 'alerta_discrepancia')
    op.drop_column('ref_booking_dam', 'ce_awb')
    # ### end Alembic commands ###
