"""add packing ogl models, weight columns and pedido table

Revision ID: 8587eb16d195
Revises: 1c4f96475710
Create Date: 2026-03-22 13:14:56.654801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8587eb16d195'
down_revision: Union[str, Sequence[str], None] = '1c4f96475710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packing_confirmaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_beta', sa.String(length=50), nullable=False),
    sa.Column('pallet_id', sa.String(length=100), nullable=False),
    sa.Column('calibre', sa.String(length=50), nullable=True),
    sa.Column('peso_neto', sa.Float(), nullable=True),
    sa.Column('fecha_cosecha', sa.Date(), nullable=True),
    sa.Column('fecha_proceso', sa.Date(), nullable=True),
    sa.Column('lote_ogl', sa.String(length=100), nullable=True),
    sa.Column('total_cajas', sa.Integer(), nullable=True),
    sa.Column('codigo_trazabilidad', sa.String(length=150), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packing_confirmaciones_orden_beta'), 'packing_confirmaciones', ['orden_beta'], unique=False)
    op.create_index(op.f('ix_packing_confirmaciones_pallet_id'), 'packing_confirmaciones', ['pallet_id'], unique=False)
    op.create_table('packing_cuadro_pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_beta', sa.String(length=50), nullable=False),
    sa.Column('product', sa.String(length=100), nullable=True),
    sa.Column('peso_caja', sa.Float(), nullable=True),
    sa.Column('house_gln', sa.String(length=50), nullable=True),
    sa.Column('cajas_por_pallet', sa.Integer(), nullable=True),
    sa.Column('additional_info', sa.String(length=255), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packing_cuadro_pedidos_orden_beta'), 'packing_cuadro_pedidos', ['orden_beta'], unique=False)
    op.create_table('packing_termografos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orden_beta', sa.String(length=50), nullable=False),
    sa.Column('pallet_id', sa.String(length=100), nullable=False),
    sa.Column('codigo_termografo', sa.String(length=100), nullable=False),
    sa.Column('fecha_subida', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_packing_termografos_orden_beta'), 'packing_termografos', ['orden_beta'], unique=False)
    op.create_index(op.f('ix_packing_termografos_pallet_id'), 'packing_termografos', ['pallet_id'], unique=False)
    op.add_column('ref_posicionamiento', sa.Column('peso_bruto', sa.Float(), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('peso_neto', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ref_posicionamiento', 'peso_neto')
    op.drop_column('ref_posicionamiento', 'peso_bruto')
    op.drop_index(op.f('ix_packing_termografos_pallet_id'), table_name='packing_termografos')
    op.drop_index(op.f('ix_packing_termografos_orden_beta'), table_name='packing_termografos')
    op.drop_table('packing_termografos')
    op.drop_index(op.f('ix_packing_cuadro_pedidos_orden_beta'), table_name='packing_cuadro_pedidos')
    op.drop_table('packing_cuadro_pedidos')
    op.drop_index(op.f('ix_packing_confirmaciones_pallet_id'), table_name='packing_confirmaciones')
    op.drop_index(op.f('ix_packing_confirmaciones_orden_beta'), table_name='packing_confirmaciones')
    op.drop_table('packing_confirmaciones')
    # ### end Alembic commands ###
