"""Add sap_codigo_cliente and sap_codigo_notify fields to CatClienteIE

Revision ID: 8cbbf3bdf54b
Revises: f8576ce1fce0
Create Date: 2026-03-18 11:21:45.592843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cbbf3bdf54b'
down_revision: Union[str, Sequence[str], None] = 'f8576ce1fce0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat_clientes_ie', sa.Column('codigo_sap_cliente', sa.String(length=50), nullable=True))
    op.add_column('cat_clientes_ie', sa.Column('codigo_sap_notify', sa.String(length=50), nullable=True))
    op.add_column('logistica_facturas', sa.Column('forma_pago', sa.String(length=100), nullable=True))
    op.add_column('logistica_facturas', sa.Column('advertencia', sa.String(length=500), nullable=True))
    op.add_column('logistica_facturas', sa.Column('descripcion', sa.String(length=500), nullable=True))
    op.add_column('logistica_facturas', sa.Column('unidad_medida', sa.String(length=10), nullable=True))
    op.alter_column('ope_registro_eventos', 'registro_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('ref_booking_dam_booking_fkey'), 'ref_booking_dam', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('ref_booking_dam_booking_fkey'), 'ref_booking_dam', 'ref_posicionamiento', ['booking'], ['booking'])
    op.alter_column('ope_registro_eventos', 'registro_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('logistica_facturas', 'unidad_medida')
    op.drop_column('logistica_facturas', 'descripcion')
    op.drop_column('logistica_facturas', 'advertencia')
    op.drop_column('logistica_facturas', 'forma_pago')
    op.drop_column('cat_clientes_ie', 'codigo_sap_notify')
    op.drop_column('cat_clientes_ie', 'codigo_sap_cliente')
    # ### end Alembic commands ###
