"""Add fecha_solicitada_operador for PDF logistics

Revision ID: 9f5b236a859b
Revises: 2abe1960980b
Create Date: 2026-03-18 17:02:21.616680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f5b236a859b'
down_revision: Union[str, Sequence[str], None] = '2abe1960980b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ref_posicionamiento', sa.Column('fecha_solicitada_operador', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ref_posicionamiento', 'fecha_solicitada_operador')
    # ### end Alembic commands ###
