"""add ubigeo to cat_plantas

Revision ID: ac2546b2bc9c
Revises: 9f5b236a859b
Create Date: 2026-03-21 15:00:21.367840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac2546b2bc9c'
down_revision: Union[str, Sequence[str], None] = '9f5b236a859b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat_plantas', sa.Column('ubigeo', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cat_plantas', 'ubigeo')
    # ### end Alembic commands ###
