"""add_fecha_status_update_to_logicapture

Revision ID: c77ac8cd78bf
Revises: 242bdc158589
Create Date: 2026-04-21 12:26:19.821832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c77ac8cd78bf'
down_revision: Union[str, Sequence[str], None] = '242bdc158589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_roles', 'permisos_plantilla',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('auth_roles', 'creado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('auth_roles', 'actualizado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('auth_roles_nombre_rol_key'), 'auth_roles', type_='unique')
    op.create_index(op.f('ix_auth_roles_nombre_rol'), 'auth_roles', ['nombre_rol'], unique=True)
    op.alter_column('auth_usuarios', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('auth_usuarios', 'requiere_cambio_password',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('auth_usuarios', 'intentos_fallidos',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('auth_usuarios', 'bloqueado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('auth_usuarios', 'permisos',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('auth_usuarios', 'creado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('auth_usuarios', 'actualizado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('auth_usuarios_usuario_key'), 'auth_usuarios', type_='unique')
    op.create_index(op.f('ix_auth_usuarios_usuario'), 'auth_usuarios', ['usuario'], unique=True)
    op.drop_constraint(op.f('choferes_dni_key'), 'choferes', type_='unique')
    op.create_index(op.f('ix_choferes_dni'), 'choferes', ['dni'], unique=True)
    op.create_index(op.f('ix_choferes_id'), 'choferes', ['id'], unique=False)
    op.create_index(op.f('ix_clientes_ie_id'), 'clientes_ie', ['id'], unique=False)
    op.drop_constraint(op.f('control_embarque_dam_key'), 'control_embarque', type_='unique')
    op.create_index(op.f('ix_control_embarque_booking'), 'control_embarque', ['booking'], unique=False)
    op.create_index(op.f('ix_control_embarque_contenedor'), 'control_embarque', ['contenedor'], unique=False)
    op.create_index(op.f('ix_control_embarque_dam'), 'control_embarque', ['dam'], unique=True)
    op.create_index(op.f('ix_control_embarque_id'), 'control_embarque', ['id'], unique=False)
    op.create_index(op.f('ix_detalle_emision_packing_list_booking'), 'detalle_emision_packing_list', ['booking'], unique=False)
    op.create_index(op.f('ix_detalle_emision_packing_list_id'), 'detalle_emision_packing_list', ['id'], unique=False)
    op.drop_constraint(op.f('detalle_emision_packing_list_emision_id_fkey'), 'detalle_emision_packing_list', type_='foreignkey')
    op.create_foreign_key(None, 'detalle_emision_packing_list', 'emision_packing_list', ['emision_id'], ['id'])
    op.create_index(op.f('ix_emision_packing_list_estado'), 'emision_packing_list', ['estado'], unique=False)
    op.create_index(op.f('ix_emision_packing_list_id'), 'emision_packing_list', ['id'], unique=False)
    op.create_index(op.f('ix_emision_packing_list_nave'), 'emision_packing_list', ['nave'], unique=False)
    op.alter_column('logicapture_detalles', 'codigo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_index(op.f('idx_det_lc_codigo'), table_name='logicapture_detalles')
    op.drop_constraint(op.f('logicapture_detalles_codigo_key'), 'logicapture_detalles', type_='unique')
    op.create_index(op.f('ix_logicapture_detalles_codigo'), 'logicapture_detalles', ['codigo'], unique=True)
    op.create_index(op.f('ix_logicapture_detalles_id'), 'logicapture_detalles', ['id'], unique=False)
    op.add_column('logicapture_registros', sa.Column('fecha_status_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('logicapture_registros', 'precinto_aduana',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('logicapture_registros', 'precinto_operador',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('logicapture_registros', 'precinto_senasa',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('logicapture_registros', 'precinto_linea',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('logicapture_registros', 'precintos_beta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('logicapture_registros', 'termografos',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('idx_lc_reg_booking'), table_name='logicapture_registros')
    op.drop_index(op.f('idx_lc_reg_contenedor'), table_name='logicapture_registros')
    op.drop_index(op.f('idx_lc_reg_dam'), table_name='logicapture_registros')
    op.create_index(op.f('ix_logicapture_registros_booking'), 'logicapture_registros', ['booking'], unique=False)
    op.create_index(op.f('ix_logicapture_registros_contenedor'), 'logicapture_registros', ['contenedor'], unique=False)
    op.create_index(op.f('ix_logicapture_registros_cultivo'), 'logicapture_registros', ['cultivo'], unique=False)
    op.create_index(op.f('ix_logicapture_registros_dam'), 'logicapture_registros', ['dam'], unique=False)
    op.create_index(op.f('ix_logicapture_registros_id'), 'logicapture_registros', ['id'], unique=False)
    op.create_index(op.f('ix_logicapture_registros_orden_beta'), 'logicapture_registros', ['orden_beta'], unique=False)
    op.create_index(op.f('ix_logicapture_registros_planta'), 'logicapture_registros', ['planta'], unique=False)
    op.create_index(op.f('ix_logicapture_registros_status'), 'logicapture_registros', ['status'], unique=False)
    op.drop_column('logicapture_registros', 'user_id')
    op.create_index(op.f('ix_maestro_fitos_id'), 'maestro_fitos', ['id'], unique=False)
    op.alter_column('ope_registro_eventos', 'antes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('ope_registro_eventos', 'despues',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.create_index(op.f('ix_ope_registro_eventos_id'), 'ope_registro_eventos', ['id'], unique=False)
    op.drop_index(op.f('idx_pc_orden_beta'), table_name='pedidos_comerciales')
    op.create_index(op.f('ix_pedidos_comerciales_id'), 'pedidos_comerciales', ['id'], unique=False)
    op.create_index(op.f('ix_pedidos_comerciales_orden_beta'), 'pedidos_comerciales', ['orden_beta'], unique=False)
    op.create_index(op.f('ix_plantas_id'), 'plantas', ['id'], unique=False)
    op.drop_index(op.f('idx_pos_booking'), table_name='posicionamientos')
    op.drop_constraint(op.f('posicionamientos_booking_key'), 'posicionamientos', type_='unique')
    op.create_index(op.f('ix_posicionamientos_booking'), 'posicionamientos', ['booking'], unique=True)
    op.create_index(op.f('ix_posicionamientos_id'), 'posicionamientos', ['id'], unique=False)
    op.create_index(op.f('ix_reporte_embarques_booking'), 'reporte_embarques', ['booking'], unique=False)
    op.create_index(op.f('ix_reporte_embarques_id'), 'reporte_embarques', ['id'], unique=False)
    op.drop_constraint(op.f('transportistas_ruc_key'), 'transportistas', type_='unique')
    op.create_index(op.f('ix_transportistas_id'), 'transportistas', ['id'], unique=False)
    op.create_index(op.f('ix_transportistas_ruc'), 'transportistas', ['ruc'], unique=True)
    op.drop_constraint(op.f('vehiculos_carreta_placa_carreta_key'), 'vehiculos_carreta', type_='unique')
    op.create_index(op.f('ix_vehiculos_carreta_id'), 'vehiculos_carreta', ['id'], unique=False)
    op.create_index(op.f('ix_vehiculos_carreta_placa_carreta'), 'vehiculos_carreta', ['placa_carreta'], unique=True)
    op.drop_constraint(op.f('vehiculos_tracto_placa_tracto_key'), 'vehiculos_tracto', type_='unique')
    op.create_index(op.f('ix_vehiculos_tracto_id'), 'vehiculos_tracto', ['id'], unique=False)
    op.create_index(op.f('ix_vehiculos_tracto_placa_tracto'), 'vehiculos_tracto', ['placa_tracto'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehiculos_tracto_placa_tracto'), table_name='vehiculos_tracto')
    op.drop_index(op.f('ix_vehiculos_tracto_id'), table_name='vehiculos_tracto')
    op.create_unique_constraint(op.f('vehiculos_tracto_placa_tracto_key'), 'vehiculos_tracto', ['placa_tracto'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_vehiculos_carreta_placa_carreta'), table_name='vehiculos_carreta')
    op.drop_index(op.f('ix_vehiculos_carreta_id'), table_name='vehiculos_carreta')
    op.create_unique_constraint(op.f('vehiculos_carreta_placa_carreta_key'), 'vehiculos_carreta', ['placa_carreta'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_transportistas_ruc'), table_name='transportistas')
    op.drop_index(op.f('ix_transportistas_id'), table_name='transportistas')
    op.create_unique_constraint(op.f('transportistas_ruc_key'), 'transportistas', ['ruc'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_reporte_embarques_id'), table_name='reporte_embarques')
    op.drop_index(op.f('ix_reporte_embarques_booking'), table_name='reporte_embarques')
    op.drop_index(op.f('ix_posicionamientos_id'), table_name='posicionamientos')
    op.drop_index(op.f('ix_posicionamientos_booking'), table_name='posicionamientos')
    op.create_unique_constraint(op.f('posicionamientos_booking_key'), 'posicionamientos', ['booking'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_pos_booking'), 'posicionamientos', ['booking'], unique=False)
    op.drop_index(op.f('ix_plantas_id'), table_name='plantas')
    op.drop_index(op.f('ix_pedidos_comerciales_orden_beta'), table_name='pedidos_comerciales')
    op.drop_index(op.f('ix_pedidos_comerciales_id'), table_name='pedidos_comerciales')
    op.create_index(op.f('idx_pc_orden_beta'), 'pedidos_comerciales', ['orden_beta'], unique=False)
    op.drop_index(op.f('ix_ope_registro_eventos_id'), table_name='ope_registro_eventos')
    op.alter_column('ope_registro_eventos', 'despues',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('ope_registro_eventos', 'antes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_maestro_fitos_id'), table_name='maestro_fitos')
    op.add_column('logicapture_registros', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_logicapture_registros_status'), table_name='logicapture_registros')
    op.drop_index(op.f('ix_logicapture_registros_planta'), table_name='logicapture_registros')
    op.drop_index(op.f('ix_logicapture_registros_orden_beta'), table_name='logicapture_registros')
    op.drop_index(op.f('ix_logicapture_registros_id'), table_name='logicapture_registros')
    op.drop_index(op.f('ix_logicapture_registros_dam'), table_name='logicapture_registros')
    op.drop_index(op.f('ix_logicapture_registros_cultivo'), table_name='logicapture_registros')
    op.drop_index(op.f('ix_logicapture_registros_contenedor'), table_name='logicapture_registros')
    op.drop_index(op.f('ix_logicapture_registros_booking'), table_name='logicapture_registros')
    op.create_index(op.f('idx_lc_reg_dam'), 'logicapture_registros', ['dam'], unique=False)
    op.create_index(op.f('idx_lc_reg_contenedor'), 'logicapture_registros', ['contenedor'], unique=False)
    op.create_index(op.f('idx_lc_reg_booking'), 'logicapture_registros', ['booking'], unique=False)
    op.alter_column('logicapture_registros', 'termografos',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('logicapture_registros', 'precintos_beta',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('logicapture_registros', 'precinto_linea',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('logicapture_registros', 'precinto_senasa',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('logicapture_registros', 'precinto_operador',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('logicapture_registros', 'precinto_aduana',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('logicapture_registros', 'fecha_status_update')
    op.drop_index(op.f('ix_logicapture_detalles_id'), table_name='logicapture_detalles')
    op.drop_index(op.f('ix_logicapture_detalles_codigo'), table_name='logicapture_detalles')
    op.create_unique_constraint(op.f('logicapture_detalles_codigo_key'), 'logicapture_detalles', ['codigo'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_det_lc_codigo'), 'logicapture_detalles', ['codigo'], unique=False)
    op.alter_column('logicapture_detalles', 'codigo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('ix_emision_packing_list_nave'), table_name='emision_packing_list')
    op.drop_index(op.f('ix_emision_packing_list_id'), table_name='emision_packing_list')
    op.drop_index(op.f('ix_emision_packing_list_estado'), table_name='emision_packing_list')
    op.drop_constraint(None, 'detalle_emision_packing_list', type_='foreignkey')
    op.create_foreign_key(op.f('detalle_emision_packing_list_emision_id_fkey'), 'detalle_emision_packing_list', 'emision_packing_list', ['emision_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_detalle_emision_packing_list_id'), table_name='detalle_emision_packing_list')
    op.drop_index(op.f('ix_detalle_emision_packing_list_booking'), table_name='detalle_emision_packing_list')
    op.drop_index(op.f('ix_control_embarque_id'), table_name='control_embarque')
    op.drop_index(op.f('ix_control_embarque_dam'), table_name='control_embarque')
    op.drop_index(op.f('ix_control_embarque_contenedor'), table_name='control_embarque')
    op.drop_index(op.f('ix_control_embarque_booking'), table_name='control_embarque')
    op.create_unique_constraint(op.f('control_embarque_dam_key'), 'control_embarque', ['dam'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_clientes_ie_id'), table_name='clientes_ie')
    op.drop_index(op.f('ix_choferes_id'), table_name='choferes')
    op.drop_index(op.f('ix_choferes_dni'), table_name='choferes')
    op.create_unique_constraint(op.f('choferes_dni_key'), 'choferes', ['dni'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_auth_usuarios_usuario'), table_name='auth_usuarios')
    op.create_unique_constraint(op.f('auth_usuarios_usuario_key'), 'auth_usuarios', ['usuario'], postgresql_nulls_not_distinct=False)
    op.alter_column('auth_usuarios', 'actualizado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('auth_usuarios', 'creado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('auth_usuarios', 'permisos',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('auth_usuarios', 'bloqueado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('auth_usuarios', 'intentos_fallidos',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('auth_usuarios', 'requiere_cambio_password',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('auth_usuarios', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_auth_roles_nombre_rol'), table_name='auth_roles')
    op.create_unique_constraint(op.f('auth_roles_nombre_rol_key'), 'auth_roles', ['nombre_rol'], postgresql_nulls_not_distinct=False)
    op.alter_column('auth_roles', 'actualizado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('auth_roles', 'creado_en',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('auth_roles', 'permisos_plantilla',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###
