"""expand_ref_posicionamiento_v2

Revision ID: f2618ae8a986
Revises: 470ff21bf728
Create Date: 2026-02-23 15:49:43.407908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2618ae8a986'
down_revision: Union[str, Sequence[str], None] = '470ff21bf728'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('auth_usuarios', 'requiere_cambio_password',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('ref_posicionamiento', sa.Column('naviera', sa.String(length=100), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('nave', sa.String(length=100), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('pol', sa.String(length=100), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('pod', sa.String(length=100), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('temperatura', sa.String(length=50), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('ventilacion', sa.String(length=50), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('planta_llenado', sa.String(length=100), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('hora_posicionamiento', sa.String(length=50), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('ac_option', sa.Integer(), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('ct_option', sa.Integer(), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('operador_logistico', sa.String(length=100), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('cultivo', sa.String(length=100), nullable=True))
    op.add_column('ref_posicionamiento', sa.Column('es_reprogramado', sa.Integer(), nullable=True))
    op.alter_column('ref_posicionamiento', 'booking',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('ref_posicionamiento', 'booking',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)
    op.drop_column('ref_posicionamiento', 'es_reprogramado')
    op.drop_column('ref_posicionamiento', 'cultivo')
    op.drop_column('ref_posicionamiento', 'operador_logistico')
    op.drop_column('ref_posicionamiento', 'ct_option')
    op.drop_column('ref_posicionamiento', 'ac_option')
    op.drop_column('ref_posicionamiento', 'hora_posicionamiento')
    op.drop_column('ref_posicionamiento', 'planta_llenado')
    op.drop_column('ref_posicionamiento', 'ventilacion')
    op.drop_column('ref_posicionamiento', 'temperatura')
    op.drop_column('ref_posicionamiento', 'pod')
    op.drop_column('ref_posicionamiento', 'pol')
    op.drop_column('ref_posicionamiento', 'nave')
    op.drop_column('ref_posicionamiento', 'naviera')
    op.alter_column('auth_usuarios', 'requiere_cambio_password',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
