"""auditoria_ondelete_set_null

Revision ID: f8576ce1fce0
Revises: 3b59aea0eec0
Create Date: 2026-03-11 17:05:38.029585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8576ce1fce0'
down_revision: Union[str, Sequence[str], None] = '3b59aea0eec0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ope_registro_eventos_registro_id_fkey'), 'ope_registro_eventos', type_='foreignkey')
    op.create_foreign_key(None, 'ope_registro_eventos', 'ope_registros', ['registro_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ope_registro_eventos', type_='foreignkey')
    op.create_foreign_key(op.f('ope_registro_eventos_registro_id_fkey'), 'ope_registro_eventos', 'ope_registros', ['registro_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
